ALTER TABLE tareas
  ADD COLUMN IF NOT EXISTS modo TEXT NOT NULL DEFAULT 'carta',
  ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES tareas(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS estado TEXT NOT NULL DEFAULT 'pendiente',
  ADD COLUMN IF NOT EXISTS cantidad NUMERIC,
  ADD COLUMN IF NOT EXISTS turno_fecha DATE,
  ADD COLUMN IF NOT EXISTS orden INTEGER NOT NULL DEFAULT 0;
